api:
  autodiscoveryId: "19980225"

bestbuy:
  host: "marketplace.bestbuy.ca"
  shopId: "5606"
  orders:
    startDate: "2024-10-17T00:00:00Z"
    batchSize: "100"
  responseTimeout: "30000"
  path: 
    fetchOrders: "/api/orders"
    updateShipment: "/api/shipments"
    updateInventory: "/api/offers"
    acceptOrders: "/api/orders/{orderId}/accept"
partnerManager:
  postOrdersUrl: "https://b2b-inbound-http-8y4p.us-e2.cloudhub.io:443/bbmporders/BBY-ORD-JSON"