name: Build and Deploy to Cloudhub Production - PROD environment

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    environment: prod
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v4
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 1.8
      uses: actions/setup-java@v4.4.0
      with:
        distribution: 'zulu'
        java-version: 8
    - name: Build with Maven
      env:
        nexus_username: ${{ secrets.NEXUS_USERNAME }}
        nexus_password: ${{ secrets.NEXUS_PASSWORD }}
        client_app_credentials: ${{ format('{0}{1}{2}', secrets.CONNECTED_APP_CLIENT_ID, '~?~', secrets.CONNECTED_APP_CLIENT_SECRET) }}
      run: mvn -B package --file pom.xml -s .maven/settings.xml
    - name: Stamp artifact file name with commit hash
      run: |
        artifactName1=$(ls target/*.jar | head -1)
        commitHash=$(git rev-parse --short "$GITHUB_SHA")
        artifactName2=$(ls target/*.jar | head -1 | sed "s/.jar/-$commitHash.jar/g")
        mv $artifactName1 $artifactName2
    - name: Upload artifact 
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: target/*.jar

  deploy:
    needs: build
    environment: prod
    runs-on: ubuntu-latest
    steps:    
    - name: Checkout this repo
      uses: actions/checkout@v4
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - uses: actions/download-artifact@v4
      with:
        name: artifacts
    - name: Deploy to Cloudhub PROD
      env:
        ID: ${{ secrets.CONNECTED_APP_CLIENT_ID }}
        SECRET: ${{ secrets.CONNECTED_APP_CLIENT_SECRET }}
        KEY: ${{ secrets.MULE_ENCRYPTION_KEY }}
        CLOUDHUB_ENV: ${{ vars.CLOUDHUB_ENV }}
        ENVIRONMENT: ${{ vars.ENVIRONMENT }}
        CLOUDHUB_ENV_CLIENT_ID: ${{ secrets.CLOUDHUB_ENV_CLIENT_ID }}
        CLOUDHUB_ENV_CLIENT_SECRET: ${{ secrets.CLOUDHUB_ENV_CLIENT_SECRET }}
      run: |
        artifactName=$(ls *.jar | head -1)
        mvn deploy -DmuleDeploy \
         -Dmule.artifact=$artifactName \
         -Dclient.id="$ID" \
         -Dclient.secret="$SECRET" \
         -Dmule.key="$KEY" \
         -Dmule.env="$ENVIRONMENT" \
         -Dcloudhub.env="$CLOUDHUB_ENV" \
         -Danypoint.platform.client_id="$CLOUDHUB_ENV_CLIENT_ID" \
         -Danypoint.platform.client_secret="$CLOUDHUB_ENV_CLIENT_SECRET"
